bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls", namespace="account")),
    path("payment/", include("payment.urls"), name="paymnet"),
    path("email/", include(email_urls), name="email-verification"),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_delete, cart_update


app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add/', cart_add, name='add-to-cart'),
    path('delete/', cart_delete, name='delete-from-cart'),
    path('update/', cart_update, name='update-from-cart'),
]

payment/urls.py
from . import views
from django.urls import path
from .webhooks import stripe_webhook

app_name = 'payment'

urlpatterns = [
    path('payment-success', views.payment_success, name='payment-success'),
    path('payment-fail', views.payment_fail, name='payment-fail'),
    path('shipping/', views.shipping, name='shipping'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete-order', views.complete_order, name='complete-order'),
    path('webhook-stripe/', stripe_webhook, name='webhook-strip'),
]

cart/views.py
from django.shortcuts import render, get_object_or_404

from shop.models import ProductProxy
from django.http import JsonResponse

from .cart import Cart


def cart_view(request):
    cart = Cart(request)

    context = {
        'cart': cart,
    }
    return render(request, 'cart/cart-view.html', context)


def cart_add(request):
    cart = Cart(request)
    
    
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))

        product_qty = int(request.POST.get('product_qty'))

        product = get_object_or_404(ProductProxy, id=product_id)

        cart.add(product=product, quantity=product_qty)

        cart.qty = cart.__len__()

        response = JsonResponse({'qty': cart.qty, "product": product.title})

        return response


def cart_delete(request):
    cart = Cart(request)

    print(request.POST.get,'**************')
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        
        cart.delete(product=product_id)
        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()
        response = JsonResponse({'qty': cart_qty, "total": cart_total})
        return response

def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        cart.update(product=product_id, quantity=product_qty)

        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()

        response = JsonResponse({'qty': cart_qty, 'total':cart_total})
        return response

cart/templates/cart/cart-view.html
{% include "base.html" %} {% load static %} {% load mathfilters %} {% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping cart</h1>

    <hr />

      {% for item in cart %}
      {% with product=item.product %}



    <br />

    <div class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{product.image.url}}"
        />
      </div>

      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a
          href="{{product.get_absolute_url}}"
          class="text-info text-decoration-none"
        >
          <h1 class="h5 pt-2">{{product.title}}</h1>
        </a>

        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Product</div>

              <div class="col-6 text-end">
                <span class="h6 fw-bold">$ {{product.price|mul:item.qty}} </span>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>

                &nbsp;

                <select id="select{{product.id}}">
                  <option selected>{{ item.qty }}</option>

                  <option value="">1</option>

                  <option value="">2</option>

                  <option value="">3</option>

                  <option value="">4</option>
                </select>

                <br />
                <br />

                <button
                  type="button"
                  data-index="{{product.id}}"
                  class="btn btn-primary btn-sm update-button"
                >
                  Update
                </button>

                &nbsp;

                <button
                  type="button"
                  class="btn btn-danger btn-sm delete-button"
                  data-index="{{product.id}}"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endwith %}
    {% endfor %}


    <div class="col-12 text-end">
      <div class="h6 fw-bold">
        Total: $
        <div id="total" class="d-inline-flex">
          {{ cart.get_total_price }}
        </div>
      </div>
    </div>
  </div>
     <button type="button" class="btn btn-success btn-md text-bg-light mt-1">
        <a class="nav-link text-decoration-none" href="{% url 'payment:checkout' %}">Checkout</a>
     </button>
  <br />
  <br />
</main>

<script>

  $(document).on('click', '.delete-button', function(e) {
    e.preventDefault();

    $.ajax({
      type: 'POST',
      url: '{% url "cart:delete-from-cart" %}',
      data: {
        product_id: $(this).attr('data-index'),
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: 'post'
      },
      success: function(response) {
        document.getElementById('lblCartCount').textContent = response.qty
        document.getElementById('total').textContent = response.total
        location.reload()
      },
      error: function(error) {
        console.log(error)
      }
    })
  })

  $(document).on('click', '.update-button', function(e) {
    e.preventDefault();

    var product_id = $(this).attr('data-index')

    $.ajax({
      type: 'POST',
      url: '{% url "cart:update-from-cart" %}',
      data: {
        product_id: $(this).attr('data-index'),
        product_qty: $('#select' + product_id+ ' option:selected').text(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: 'post'
      },
      success: function(response) {
        document.getElementById('lblCartCount').textContent = response.qty
        document.getElementById('total').textContent = response.total
        location.reload()
      },
      error: function(error) {
        console.log(error)
      }
    })
  })
</script> 

{% endblock %}