account/urls.py
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.urls import path, reverse_lazy

from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path(
        "email-verification-sent/",
        lambda request: render(request, "account/email/email-verification-sent.html"),
        name="email-verification-sent",
    ),
    path("dashboard/", views.dashboard_user, name="dashboard"),
    path("profile-manager", views.profile_user, name="profile-manager"),
    path("delete-user", views.delete_user, name="delete-user"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password/password-reset.html",
            email_template_name="account/password/password-reset-email.html",
            success_url=reverse_lazy("account:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/password/password-reset-done.html"
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password/password-reset-confirm.html",
            success_url=reverse_lazy("account:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password/password-reset-complete.html"
        ),
        name="password_reset_complete",
    ),
]

bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls", namespace="account")),
    path("payment/", include("payment.urls"), name="paymnet"),
    path("email/", include(email_urls), name="email-verification"),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_delete, cart_update


app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add/', cart_add, name='add-to-cart'),
    path('delete/', cart_delete, name='delete-from-cart'),
    path('update/', cart_update, name='update-from-cart'),
]

shop/urls.py
from django.urls import path
from .views import products_detail_view, products_view, category_list


app_name = 'shop'

urlpatterns = [
    path('', products_view, name='products'),
    path('<slug:slug>/', products_detail_view, name='product-detail'),
    path('search/<slug:slug>/', category_list, name='category-list'),
]

shop/models.py
import random
import string

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def rand_slug():
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))


class Category(models.Model):
    name = models.CharField("Категория" ,max_length=250, db_index=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)
    slug = models.SlugField('URL',max_length=250, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания',auto_now_add=True)

    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + '-pickBetter' +self.name)
        super(Category, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("shop:category-list", args=[str(self.slug)])
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name = 'products')
    title = models.CharField("Название", max_length=250)
    brand = models.CharField("Бренд", max_length=250)
    description = models.TextField("Описание", blank=True)
    slug = models.SlugField('URL', max_length=250)
    price = models.DecimalField("Цена", max_digits=7, decimal_places = 2, default=99.99)
    image = models.ImageField("Изображение", upload_to='products/products/%Y/%m/%d')
    available = models.BooleanField("Наличие", default = True)
    created_at = models.DateTimeField('Дата создания', auto_now_add = True)
    updated_at = models.DateTimeField('Дата Изменения', auto_now = True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[str(self.slug)])
    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(available=True)


class ProductProxy(Product):

    objects = ProductManager()

    class Meta:
        proxy = True

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, ProductProxy


def products_view(request):
    products = ProductProxy.objects.all()
    return render(request, 'shop/products.html', {'products': products})

def products_detail_view(request, slug):
    product = get_object_or_404(ProductProxy, slug=slug)
    return render(request, 'shop/product_detail.html', {'product': product})

def category_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = ProductProxy.objects.select_related('category').filter(category=category)
    context = {'category': category, 'products': products}
    return render(request, 'shop/category_list.html', context)

shop/templates/shop/_partials/_footer.html
 <!-- Footer -->
 <footer id="main-footer" class="py-4 --bs-light-bg-subtle text-dark text-center">
    Copyright &copy;
    <span class="year"></span> BigCorp Shop
  </footer>

shop/templates/shop/_partials/_head_imports.html
<!-- CSS -->

<link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

<!-- JavaScript -->

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<!-- JavaScript Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

shop/templates/shop/_partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm ">
    <div class="container">
        <a class="navbar-brand" href="{% url 'shop:products' %}"><i class="fa-solid fa-shop me-2"></i>
            <strong>BigCorp SHOP</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form action="" method="get">
            <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
            <div class="input-group">
                <span class="border-success input-group-text bg-success text-white"><i
                        class="fa-solid fa-magnifying-glass"></i></span>
                <input type="text" name="q" placeholder="ex. Samsung" class="form-control border-success" style="color: #7a7a7a" />
                <button class="btn btn-success text-dark search-button">Search</button>
            </div>
        </div>
    </form>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <form action="" method="get">
            <div class="ms-auto d-none d-lg-block">
                <div class="input-group">
                    <span class="border-success input-group-text text-white search-button"><i
                            class="fa-solid fa-magnifying-glass"></i></span>
                    <input type="text" name="q" placeholder="ex. Samsung" class="form-control border-success" style="color: #7a7a7a" />
                    <button class="btn btn-success text-dark search-button">Search</button>
                </div>
            </div>
        </form>
            <ul class="navbar-nav ms-auto">
                {% for i in categories %}

                {% if not i.children.all %}
                <li class="nav-item">
                    <a class="nav-link" href="{{i.get_absolute_url}}">{{i.name|upper }}</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{{i.get_absolute_url}}" id="navbarDropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{i.name|upper}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% for obj in i.children.all %} {% if not obj.children.all %}
                        <li><a class="dropdown-item" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a></li>
                        {% else %}
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle"
                                href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a>

                            <ul class="dropdown-menu">
                                {% for subobj in obj.children.all %} {% if not subobj.children.all %}
                                <li>
                                    <a class="dropdown-item"
                                        href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>
                                </li>
                                {% else %}
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle"
                                        href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>

                                    <ul class="dropdown-menu">
                                        {% for lastobj in subobj.children.all %}
                                        <li>
                                            <a class="dropdown-item"
                                                href="{{lastobj.get_absolute_url}}">{{lastobj.name|upper}}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endif %} {% endfor %}
                            </ul>
                        </li>
                        {% endif %} {% endfor %}
                    </ul>
                </li>
                {% endif %} {% endfor %}
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'cart:cart-view' %}"> <i
                            class="fa fa-shopping-cart" aria-hidden="true"> </i> Cart
                        <span id="lblCartCount" class="badge badge-success ">

                            {% with cart_qty=cart|length%}
                            {% if cart_qty > 0 %}
                            {{cart_qty}}
                            {% else %}
                            0
                            {% endif %}

                            {% endwith %}
                        </span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:dashboard' %}"><i
                            class="fa-solid fa-circle-user me-1"></i>@{{ user.username }} Account</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:logout' %}"><i
                            class="fa-solid fa-circle-user me-1"></i> Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:register' %}"><i
                            class="fa-solid fa-circle-user me-1"></i> Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url 'account:login' %}"><i
                            class="fa-solid fa-circle-user me-1"></i> Login</a>
                </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>