bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls", namespace="account")),
    path("payment/", include("payment.urls"), name="paymnet"),
    path("email/", include(email_urls), name="email-verification"),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_delete, cart_update


app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add/', cart_add, name='add-to-cart'),
    path('delete/', cart_delete, name='delete-from-cart'),
    path('update/', cart_update, name='update-from-cart'),
]

shop/urls.py
from django.urls import path
from .views import products_detail_view, products_view, category_list


app_name = 'shop'

urlpatterns = [
    path('', products_view, name='products'),
    path('<slug:slug>/', products_detail_view, name='product-detail'),
    path('search/<slug:slug>/', category_list, name='category-list'),
]

shop/models.py
import random
import string

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def rand_slug():
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))


class Category(models.Model):
    name = models.CharField("Категория" ,max_length=250, db_index=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)
    slug = models.SlugField('URL',max_length=250, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания',auto_now_add=True)

    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + '-pickBetter' +self.name)
        super(Category, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("shop:category-list", args=[str(self.slug)])
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name = 'products')
    title = models.CharField("Название", max_length=250)
    brand = models.CharField("Бренд", max_length=250)
    description = models.TextField("Описание", blank=True)
    slug = models.SlugField('URL', max_length=250)
    price = models.DecimalField("Цена", max_digits=7, decimal_places = 2, default=99.99)
    image = models.ImageField("Изображение", upload_to='products/products/%Y/%m/%d')
    available = models.BooleanField("Наличие", default = True)
    created_at = models.DateTimeField('Дата создания', auto_now_add = True)
    updated_at = models.DateTimeField('Дата Изменения', auto_now = True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[str(self.slug)])
    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(available=True)


class ProductProxy(Product):

    objects = ProductManager()

    class Meta:
        proxy = True

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, ProductProxy


def products_view(request):
    products = ProductProxy.objects.all()
    return render(request, 'shop/products.html', {'products': products})

def products_detail_view(request, slug):
    product = get_object_or_404(ProductProxy, slug=slug)
    return render(request, 'shop/product_detail.html', {'product': product})

def category_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = ProductProxy.objects.select_related('category').filter(category=category)
    context = {'category': category, 'products': products}
    return render(request, 'shop/category_list.html', context)

shop/templates/shop/category_list.html
{% extends "base.html" %}

{% load static %}


{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{category.name|capfirst}} </div>


      <hr>

      <br>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-info text-decoration-none" href="{{product.get_absolute_url}}"> {{product.title|capfirst}} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <h5> $ {{product.price}} </h5>
              </div>
            </div>
          </div>
        </div>

       {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{product.image.url}}"> <!-- Product image -->

            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{product.name}}</h1>

                <strong>{{product.brand}}</strong>


                <hr>

                <br>


                <p> {{product.description}} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">

                            <div class="col-6"> Price </div>

                            <div class="col-6 text-end"><span class="h4 fw-bold">$ {{product.price}}</span></div>

                        </div>

                    </div>

                    <div class="col">

                        <div class="row p-3">

                            <div class="col-6">


                                <label for="select">Qty</label>

                                &nbsp; 

                                <select id="select">

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                </select>

                            </div>

                            <div class="col-6 text-end">

                                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">

                                Add to cart 

                                </button> 


                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </main>

    <br>

</div>

<script>
    $(document).on('click', '#add-button', function(e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:add-to-cart" %}',
            data: {
                product_id: $('#add-button').val(),
                product_qty: $('#select option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response) {
                document.getElementById('lblCartCount').textContent = response.qty
            },
            error: function(error) {
                console.log(error)
            }
        })
    })
</script>

{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %}


{% block content %}

<!-- Introduction section -->
<section class="py-4 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h4>Choose and it is in your hands.</h4>

      <br />

      <p class="lead text-muted">Browse and make the best deal</p>

      <br />

      <a href="#" class="btn btn-success my-2"> Create an account </a>
    </div>
  </div>
</section>

<!-- All products section -->

<section class="album py-5 bg-light">
  <div class="container">
    <div class="pb-3 h5">All products</div>

    <hr />

    <br />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% include 'shop/components/product_list.html' %}
    </div>
  </div>
</section>
{% endblock %}