bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls", namespace="account")),
    path("payment/", include("payment.urls"), name="paymnet"),
    path("email/", include(email_urls), name="email-verification"),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_delete, cart_update


app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add/', cart_add, name='add-to-cart'),
    path('delete/', cart_delete, name='delete-from-cart'),
    path('update/', cart_update, name='update-from-cart'),
]

payment/urls.py
from . import views
from django.urls import path
from .webhooks import stripe_webhook

app_name = 'payment'

urlpatterns = [
    path('payment-success', views.payment_success, name='payment-success'),
    path('payment-fail', views.payment_fail, name='payment-fail'),
    path('shipping/', views.shipping, name='shipping'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete-order', views.complete_order, name='complete-order'),
    path('webhook-stripe/', stripe_webhook, name='webhook-strip'),
]

payment/models.py
from django.db import models
from django.contrib.auth import get_user_model

from shop.models import Product

User = get_user_model()


class ShippingAdress(models.Model):
    full_name = models.CharField(max_length=250)
    email = models.EmailField(max_length=254)

    street_adress = models.CharField(max_length=250)
    apartment_adress = models.CharField(max_length=250)
    
    country = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    zip_code = models.CharField(max_length=100, blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Shipping Address" + str(self.id)
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    shipping_address = models.ForeignKey(ShippingAdress, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return "Order " + str(self.id)
    


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(
    User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "OrderItem" + str(self.id)

payment/forms.py
from django import forms

from .models import ShippingAdress


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAdress
        fields = ['full_name', 'email', 'street_adress', 'apartment_adress', 'country','zip_code']
        exclude = ['user']

payment/views.py
from decimal import Decimal
from django.http import JsonResponse

import stripe
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings

from cart.cart import Cart

from .forms import ShippingAddressForm
from .models import Order, OrderItem, ShippingAdress

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


@login_required(login_url="account:login")
def shipping(request):
    try:
        shipping_adress = ShippingAdress.objects.get(user=request.user)
    except ShippingAdress.DoesNotExist:
        shipping_adress = None

    form = ShippingAddressForm(instance=shipping_adress)

    if request.method == "POST":
        form = ShippingAddressForm(request.POST, instance=shipping_adress)
        if form.is_valid():
            shipping_adress = form.save(commit=False)
            shipping_adress.user = request.user
            shipping_adress.save()
            return redirect("account:dashboard")
    return render(request, "payment/shipping.html", {"form": form})


def checkout(request):
    if request.user.is_authenticated:
        shipping_adress = get_object_or_404(ShippingAdress, user=request.user)
        if shipping_adress:
            return render(
                request, "payment/checkout.html", {"shipping_adress": shipping_adress}
            )
    return render(request, "payment/checkout.html")


def complete_order(request):
    if request.method == "POST":
        payment_type = request.POST.get("stripe-payment", "yookassa-payment")
        name = request.POST.get("name")
        email = request.POST.get("email")
        street_address = request.POST.get("street_address")
        apartment_address = request.POST.get("apartment_address")
        country = request.POST.get("country")
        zip = request.POST.get("zip")

        cart = Cart(request)
        total_price = cart.get_total_price()

        shipping_address, _ = ShippingAdress.objects.get_or_create(
            user=request.user,
            defaults={
                "name": name,
                "email": email,
                "street_address": street_address,
                "apartment_address": apartment_address,
                "country": country,
                "zip": zip,
            },
        )

        match payment_type:
            case "stripe-payment":
                session_data = {
                    "mode": "payment",
                    "success_url": request.build_absolute_uri(
                        reverse("payment:payment-success")
                    ),
                    "cancel_url": request.build_absolute_uri(
                        reverse("payment:payment-fail")
                    ),
                    "line_items": [],
                }

                if request.user.is_authenticated:
                    order = Order.objects.create(
                        user=request.user,
                        shipping_address=shipping_address,
                        amount=total_price,
                    )

                    for item in cart:
                        OrderItem.objects.create(
                            order=order,
                            product=item["product"],
                            price=item["price"],
                            quantity=item["qty"],
                            user=request.user,
                        )

                        session_data["line_items"].append(
                            {
                                "price_data": {
                                    "unit_amount": int(item["price"] * Decimal(100)),
                                    "currency": "usd",
                                    "product_data": {"name": item["product"]},
                                },
                                "quantity": item["qty"],
                            }
                        )

                        session = stripe.checkout.Session.create(**session_data)
                        session_data['client_reference_id'] = order.id
                        return redirect(session.url, code=303)
                else:
                    order = Order.objects.create(
                        shipping_address=shipping_address, amount=total_price
                    )

                    for item in cart:
                        OrderItem.objects.create(
                            order=order,
                            product=item["product"],
                            price=item["price"],
                            quantity=item["qty"],
                        )
                        session_data["line_items"].append(
                            {
                                "price_data": {
                                    "unit_amount": int(item["price"] * Decimal(100)),
                                    "currency": "usd",
                                    "product_data": {"name": item["product"]},
                                },
                                "quantity": item["qty"],
                            }
                        )

                        session = stripe.checkout.Session.create(**session_data)
                        session_data['client_reference_id'] = order.id
                        return redirect(session.url, code=303)


def payment_success(request):
    for key in list(request.session.keys()):
        if key == "session_key":
            del request.session[key]
    return render(request, "payment/payment-success.html")


def payment_fail(request):
    return render(request, "payment/payment-fail.html")

payment/templates/payment/checkout.html
{% include "base.html" %}


{% load static %}


{% block content %}

<style>

    body 
    {

        background-color: gray;

    }


</style>


    <body>

        <br>

        <div class="container bg-white shadow-md p-5" style="width:500px; border-radius:20px;">

                <form id="form" action="{% url 'payment:complete-order' %}" method="post">
                <div>

                    <h3> <i class="fa fa-chevron-circle-right" aria-hidden="true"></i> &nbsp; Complete your order </h3>

                    <p> Please enter in the relevant information below. </p>



                    <hr>

                    <br>

                    <div class="form-field">

                        <input class="form-control validate" id="name" type="text" placeholder="Full name*" autocomplete="off" value="{{shipping_address.full_name}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="email" type="email" placeholder="Email address*" autocomplete="off" value="{{shipping_address.email}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="address1" type="text" placeholder="Street address*" autocomplete="off" value="{{shipping_address.street_address}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="address2" type="text" placeholder="Apartment address" autocomplete="off" value="{{shipping_address.apartment_address}}" required>

                    </div>


                    <br>


                  <div class="form-field">

                        <input class="form-control validate" id="city" type="text" placeholder="City*" autocomplete="off" value="{{shipping_address.city}}" required>

                    </div> 


                    <br>


                    <div class="form-field">

                        <input class="form-control" id="state" type="text" placeholder="Country" autocomplete="off" value="{{shipping_address.country}}">

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control" id="zipcode" type="text" placeholder="Zip code (Optional)" autocomplete="off" value="{{shipping_address.zip}}">

                    </div>

                </div>

                <br>
                    {% csrf_token %}


               <button id="complete-order-stripe" type="submit" class="btn btn-primary navbar-btn text-white" name='stripe-payment' value="stripe-payment"> &nbsp; Pay with stripe </button>
               <button id="complete-order" type="submit" class="btn btn-primary navbar-btn text-white"> &nbsp; Complete order </button>


                <br>




            </form>


        </div>



        <br>


    </body>
 
{% endblock %}

payment/templates/payment/payment-fail.html
{%  extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'payment/css/payment-success-fail.css' %}">
{% endblock head %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <div class="message-box _success _failed">
            <i class="fa fa-times-circle" aria-hidden="true"></i>
            <h2> Your payment failed </h2>
            <p> Try again later </p>
        </div>
    </div>
</div>
</div>
{% endblock content %}

payment/templates/payment/payment-success.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'payment/css/payment-success-fail.css' %}">
{% endblock head %}

{% block content %}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-5 ">
            <div class="message-box _success">
                <i class="fa fa-check-circle" aria-hidden="true"></i>
                <h2> Your payment was successful </h2>
                <p> Thank you for your payment. we will <br>
                    be in contact with more details shortly </p>
            </div>
        </div>
    </div>

{% endblock content %}

payment/templates/payment/shipping.html
{%  include "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container bg-white shadow-md p-5 form-layout">

    <h3>Shipping</h3>

    <br>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary w-100 btn-block p-2 btn-register">Save</button>
    </form>

    <br>

    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}

            </li>
        {% endfor %}
    </ul>
{% endif %}


</div>

<br>

{% endblock content %}